apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-prilogenie
  namespace: netology
  labels:
    app: t-pril
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t-pril
  template:
    metadata:
      namespace: netology
      labels:
        app: t-pril
    spec:
      containers:
      - name: test-prilogenie-site
        image: artmur18/diplom-nginx:v1.2.10
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-test-prilogenie
  namespace: netology
spec:
  selector:
    app: t-pril
  ports:
    - name: service-t-prilogenie
      protocol: TCP
      port: 80
      nodePort: 31080
  type: NodePort